spring:
  #通用数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db_mall?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: wh001225

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.mall.coupon.model

# 显示SQL语句部分
logging:
  level:
    com:
      example:
        mall:
          coupon:
            mapper: debug

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000